config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root"examples#home"
  get "about", to: "examples#about"

  resources :articles

  get "signup", to: "users#new"
  resources :users, except:[:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :categories

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories  
  validates :title, presence:true, length:{minimum:3, maximum:30}
  validates :description, presence:true, length:{minimum:10, maximum:300}
  validates :user_id, presence: true

end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true,
            length: { minimum: 3, maximum: 50},
            uniqueness: { case_sensitive: false }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
                     uniqueness: { case_sensitive: false },
                     length: { minimum: 3, maximum: 50 }
  validate_email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                  length: { maximum: 50},
                  uniqueness: { case_sensitive: false },
                  format: { with: validate_email_regex}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be log in to perform that task"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:show, :edit, :update, :destroy]
before_action :require_user, except: [:index, :show]
before_action :require_same_user, only: [:edit, :update, :destroy]
def index
  @articles = Article.paginate(page: params[:page], per_page: 5 )
end

def new

  @article = Article.new
end



def create
  @article = Article.new(article_params)
  @article.user = current_user
  if @article.save
    flash[:success] = "Article is created sucessfully!!"
    redirect_to article_path(@article)
  else
    render 'new'
  end
end



def show
end



def edit
end


def update
  if @article.update(article_params)
    flash[:success] = "Article is updated sucessfully!!"
    redirect_to article_path(@article)
  else
    render 'edit'

  end


end


def destroy
  @article.destroy
  flash[:danger] = "Article is deleted sucessfully!!"
  redirect_to articles_path
end



private
  def set_article
    @article = Article.find(params[:id])
  end
  def article_params
    params.require(:article).permit(:title, :description)
  end
  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only update/delete your own article"
      redirect_to root_path
    end
  end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, only: [:new, :create]


  def index
      @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "New category added successfully !!!"
      redirect_to category_path(@category)
    else
      flash[:danger] = "Something went wrong !!!"
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
  end


  private
    def category_params
      params.require(:category).permit(:name)

    end

    def require_admin
      if !logged_in? || (logged_in? and !current_user.admin?)
        flash[:danger] = "only admin can create new category"
        redirect_to categories_path

      end

    end


end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create

    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have log in successfully!!"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "somthing went wrong with logg in credentials"
      render 'new'

    end
  end
  def destroy
    session[:user_id] = nil
    flash[:success] = "you have log out successfully !! "
    redirect_to root_path

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

def index
  @users = User.paginate(page: params[:page], per_page: 5 )
end

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    flash[:success] = "Welcome to Test Application     #{@user.username}"
    redirect_to user_path(@user)
  else
    render 'new'
  end

end

def edit
end

def update
  if @user.update(user_params)
    flash[:success] = "Successfully Updated User"
    redirect_to articles_path
  else
    render 'edit'
  end

end

def destroy
    @user.destroy
    flash[:danger] = "User with all article associated to that user is deleted"
    redirect_to users_path
end


def show
  @user_article = @user.articles.paginate(page: params[:page], per_page: 5)
end





private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end



  def set_user
    @user = User.find(params[:id])
  end


  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit/delete your own account"
      redirect_to root_path

    end
  end


  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "only admin can perform that action"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt:user.username, class: "img-circle")

  end

end

app/views/articles/_article.html.erb
<table>
<tr>
  <th>title</th>
  <th>description</th>
</tr>
<% obj.each do |article| %>
<tr>
   <td><%= article.title %></td>
   <td><%= truncate(article.description, length:100) %></td>
    <% if logged_in? &&  (current_user == article.user || current_user.admin?) %>
      <td class="btn btn-info btncustom"><%= link_to "edit", edit_article_path(article) %></td>
      <td class="btn btn-info btncustom"><%= link_to "show", article_path(article) %></td>
      <td class="btn btn-info btncustom"><%= link_to "delete", article_path(article), method: :delete, data: {confirm: "are you sure to delete that??"} %></td>
    <% end %>
 </tr>
 <% end %>
 </table>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%= form_for @article do |f| %>
<p>
  <%= f.label :title%><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :description%><br>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

<%= link_to "back to list", articles_path %>

app/views/articles/_message.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg|%>
      <div class='alert alert-<%="#{name}"%>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>edit page</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing Articles </h1>
<%= link_to "create new article", new_article_path %>
<%= link_to "Home", root_path %>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1> Add new article </h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Show template</h1>

<p>title: <%= @article.title%></p>
<p>description: <%= @article.description %></p>

app/views/categories/index.html.erb
<h1 align="center"> Categories Listing</h1>
<div class="center">
  <ul class="listing">
    <div align="center">
      <%= will_paginate %>
    </div>

    <div class="row">
      <div class="col-xs-4 col-xs-offset-4 center">
        <% @categories.each do |category| %>
        <div align="center">

          <li class="category_listing "><%= link_to category.name, category_path(category) %></li>
        </div>
        <% end %>
      </div>
    </div>
    <div align="center">

      <%= will_paginate %>
    </div>
  </ul>
</div>

app/views/categories/new.html.erb
<h1 align="center" >Add New Category</h1>
<%= form_for(@category , :html => {class: "form-horizontal", role: "form"}) do |f| %>

<div class="form-group">

<div class="control-label col-sm-2">

<%= f.label :name %>

</div>

<div class="col-sm-8">

<%= f.text_field :name, class: "form-control", placeholder: "Enter New Category Name", autofocus: true %>

</div>

</div>

<div class="form-group">

<div class="col-sm-offset-2 col-sm-10">

<%= f.submit "Add Category", class: 'btn btn-primary btn-lg' %>

</div>

</div>

<% end %>

app/views/categories/show.html.erb
<h1 align="center">show</h1>

app/views/examples/about.html.erb
<h1>About page</h1>

app/views/examples/home.html.erb
<div class="jumbotron">
  <h1>Rails Blog App</h1>
  <p><%= link_to "Sign Up", signup_path, class: "btn btn-danger btn-lg" %></p>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Example Test App', root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Article', articles_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'new Article', new_article_path%></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "log out", logout_path, method: :delete %></li>
        <%else%>
          <li><%= link_to "log in", login_path %></li>
          <li><%= link_to "sign in", signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeTestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'articles/message'%>
      <div class="container">
        <%= yield %>
      </div>

  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2 ">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error")%>
              found !!!
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |errormsg| %>
                <li><%=errormsg%></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<%= form_for @user do |f| %>
<p>
  <%= f.label :username%><br>
  <%= f.text_field :username %>
</p>
<p>
  <%= f.label :email%><br>
  <%= f.email_field :email %>
</p>
<p>
  <%= f.label :password%><br>
  <%= f.password_field :password %>
</p>
<p>
  <%= f.submit (@user.new_record? ? "Signup" : "Update") %>
</p>

<% end %>

<%= link_to "back to list", articles_path %>

app/views/users/edit.html.erb
<h1>Edit User For This Application</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">List of Users</h1>
<div align="center">


<%= will_paginate %>
<% @users.each do |user|%>
<div class="well">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
      <%= gravatar_for user, size: 150 %>
    </div>
  </div>
  <h4 align="center"><%= user.username %></h4>
  <%= link_to "delete the user", user_path(user), method: :delete,data: {confirm: "Are you shure to delete user with articles?"} if logged_in? and current_user.admin? %>
</div>
<% end %>
<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1>SignUp For This Application</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%=@user.username%>'s page</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>

<h4 align= "center"><%= @user.username %>'s Articles</h4>
<div class="center">
  <%= will_paginate @user_article%>
</div>

<%= render 'articles/article', obj: @user_article%>
<div class="center">
  <%= will_paginate @user_article%>
</div>